baseURL: https://eugene-nesterenko-lbs.netlify.app
languageCode: en-us
title: Personal website by Eugene Nesterenko
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    #subtitle: |- 
    #   A RESPONSIVE SITE TEMPLATE DESIGNED BY HTML5 UP
    #   AND RELEASED UNDER THE CREATIVE COMMONS.
    title: Hi, my name is Eugene Nesterenko
    subtitle: I am a student at London Business School, and I am taking my first steps in Data Science
  blog: {}
  contact:
    address:
      - city: London, NW8 7AD
        country:  United Kingdom
        street: Robin House, Barrow Hill Estate
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: enesterenko.mba2024@london.edu
        title: Email
    enable: yes
    phone:
      - phone: +44(734) 297-****
        title: Phone
  custom_css: []
  custom_js: []
  description: Personal website by Eugene Nesterenko. Data analytics results may be used freely in educational purposes.
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Eugene Nesterenko
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      # - icon: fa-twitter
      #   label: Twitter
      #   url: https://www.twitter.com
      # - icon: fa-facebook
      #   label: Facebook
      #   url: https://www.facebook.com
      # - icon: fa-instagram
      #   label: Instagram
      #   url: https://www.instagram.com
      - icon: fa-github
        label: GitHub
        url: https://github.com/YevheniiN281
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/eugene-nesterenko/
      - icon: fa-file-alt
        label: CV
        url: https://www.linkedin.com/in/eugene-nesterenko/
  image: 'Eugene Nesterenko formal.jpeg'
  name: Eugene Nesterenko
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: Generic Blog
        url: blogs/ipsum
      - name: Elements
        url: elements.html
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: pic01.jpg
        subtitle: Ipsum Dolor Sit Amet
        title: Aliquam
        url: blogs/blog4
      - image: pic02.jpg
        # subtitle: My CV
        title: My CV
        url: blogs/Eugene_Nesterenko_CV.pdf
      - image: Eugene_Nesterenko_formal.jpeg
        # subtitle: Image library
        title: Image library
        url: blogs/Eugene_Nesterenko_formal.jpeg
      - image: pic04.jpg
        subtitle: A new web page with a CV
        title: My CV 2
        url: blogs/CV_page.html
      - image: pic05.jpg
        subtitle: Ipsum Dolor Sit Amet
        title: Consequat
        url: blogs/ipsum
      - image: Bechdel_test_image.jpg
        subtitle: I use various regression and ML models to predict whether a movie will pass a Bechdel test
        title: Bechdel test predictions
        url: blogs/Bechdel.html
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.
      \n    Mauris aliquet magna magna sed nunc rhoncus pharetra. \n    Pellentesque
      condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia
      pellentesque lorem ipsum dolor. \n    Nullam et orci eu lorem consequat tincidunt.
      Vivamus et sagittis libero.\n    Mauris aliquet magna magna sed nunc rhoncus
      amet pharetra et feugiat tempus."
    title: Massa libero
    url: blogs
    
markup: 
  goldmark: 
    renderer: 
      unsafe: true
      
